# Generated by Django 5.1.1 on 2025-06-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0007_participant_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='dept',
            field=models.CharField(choices=[('cs', 'CS'), ('it', 'IT'), ('entc', 'ENTC'), ('civil', 'CIVIL'), ('mechanical', 'MECHANICAL'), ('aids', 'AIDS'), ('aiml', 'AIML'), ('mba', 'MBA'), ('mca', 'MCA'), ('pharmacy', 'PHARMACY')], default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
